version: '3'

services:
  app:
    build:
      context: .
    environment:
      - FLASK_ENV=production
    env_file:
      - .env-prod
    command: gunicorn --bind '0.0.0.0:5000' app:app
    ports:
      - '5000:5000'
